// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tasawr.standupmanager.domain;

import com.tasawr.standupmanager.domain.StandupDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect StandupDataOnDemand_Roo_Configurable {
    
    declare @type: StandupDataOnDemand: @Configurable;
    
}
