// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tasawr.standupmanager.domain;

import com.tasawr.standupmanager.domain.Standup;
import com.tasawr.standupmanager.domain.StandupDataOnDemand;
import com.tasawr.standupmanager.domain.StandupIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect StandupIntegrationTest_Roo_IntegrationTest {
    
    declare @type: StandupIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: StandupIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: StandupIntegrationTest: @Transactional;
    
    @Autowired
    StandupDataOnDemand StandupIntegrationTest.dod;
    
    @Test
    public void StandupIntegrationTest.testCountStandups() {
        Assert.assertNotNull("Data on demand for 'Standup' failed to initialize correctly", dod.getRandomStandup());
        long count = Standup.countStandups();
        Assert.assertTrue("Counter for 'Standup' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void StandupIntegrationTest.testFindStandup() {
        Standup obj = dod.getRandomStandup();
        Assert.assertNotNull("Data on demand for 'Standup' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Standup' failed to provide an identifier", id);
        obj = Standup.findStandup(id);
        Assert.assertNotNull("Find method for 'Standup' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Standup' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void StandupIntegrationTest.testFindAllStandups() {
        Assert.assertNotNull("Data on demand for 'Standup' failed to initialize correctly", dod.getRandomStandup());
        long count = Standup.countStandups();
        Assert.assertTrue("Too expensive to perform a find all test for 'Standup', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Standup> result = Standup.findAllStandups();
        Assert.assertNotNull("Find all method for 'Standup' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Standup' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void StandupIntegrationTest.testFindStandupEntries() {
        Assert.assertNotNull("Data on demand for 'Standup' failed to initialize correctly", dod.getRandomStandup());
        long count = Standup.countStandups();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Standup> result = Standup.findStandupEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Standup' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Standup' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void StandupIntegrationTest.testFlush() {
        Standup obj = dod.getRandomStandup();
        Assert.assertNotNull("Data on demand for 'Standup' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Standup' failed to provide an identifier", id);
        obj = Standup.findStandup(id);
        Assert.assertNotNull("Find method for 'Standup' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyStandup(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Standup' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void StandupIntegrationTest.testMergeUpdate() {
        Standup obj = dod.getRandomStandup();
        Assert.assertNotNull("Data on demand for 'Standup' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Standup' failed to provide an identifier", id);
        obj = Standup.findStandup(id);
        boolean modified =  dod.modifyStandup(obj);
        Integer currentVersion = obj.getVersion();
        Standup merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Standup' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void StandupIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Standup' failed to initialize correctly", dod.getRandomStandup());
        Standup obj = dod.getNewTransientStandup(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Standup' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Standup' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Standup' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void StandupIntegrationTest.testRemove() {
        Standup obj = dod.getRandomStandup();
        Assert.assertNotNull("Data on demand for 'Standup' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Standup' failed to provide an identifier", id);
        obj = Standup.findStandup(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Standup' with identifier '" + id + "'", Standup.findStandup(id));
    }
    
}
