// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tasawr.standupmanager.domain;

import com.tasawr.standupmanager.domain.Roles;

privileged aspect Roles_Roo_JavaBean {
    
    public String Roles.getRoleName() {
        return this.roleName;
    }
    
    public void Roles.setRoleName(String roleName) {
        this.roleName = roleName;
    }
    
}
